version: '2'

services:
  foo-service:
    build: .
    ports:
        - "3000:3000"
    volumes:
        - .:/code
        - /code/node_modules
    command: npm run dev
    environment:
        NODE_ENV: 'development'
